/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class www_seven_com_jni_android_mk_MainActivity */

#ifndef _Included_www_seven_com_jni_android_mk_MainActivity
#define _Included_www_seven_com_jni_android_mk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     www_seven_com_jni_android_mk_MainActivity
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_www_seven_com_jni_1android_1mk_MainActivity_getStringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
